apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        tier: backend
        track: stable
    spec:
      containers:
      - name: user-service
        image: paolobonicco/user-service:v0.8
        ports:
          - containerPort: 8080
        env:
          - name: DB_URL
            value: "jdbc:postgresql://34.65.114.98:5432/user-db"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: db-username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: LoadBalancer
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080