apiVersion: apps/v1
kind: Deployment
metadata:
  name: hobbit-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hobbit-user
  template:
    metadata:
      labels:
        app: hobbit-user
        tier: backend
        track: stable
    spec:
      containers:
      - name: hobbit-user
        image: paolobonicco/hobbit-user:v0.1
        ports:
          - containerPort: 8082
        env:
          - name: DB_URL
            value: "jdbc:postgresql://34.65.114.98:5432/user-db"
          - name: DB_USERNAME
            value: aG9iYml0
          - name: DB_PASSWORD
            value: RWg/M1V+X3NoI1hAdSYrSw==
---
apiVersion: v1
kind: Service
metadata:
  name: hobbit-user
spec:
  selector:
    app: hobbit-user
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082