apiVersion: apps/v1
kind: Deployment
metadata:
  name: hobbit-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hobbit-user
  template:
    metadata:
      labels:
        app: hobbit-user
        tier: backend
        track: stable
    spec:
      containers:
      - name: hobbit-user
        image: paolobonicco/hobbit-user:v1.1
        ports:
          - containerPort: 8082
        env:
          # - name: DB_URL
          #   value: "jdbc:postgresql://34.65.114.98:5432/user-db"
          # - name: DB_USERNAME
          #   value: hobbit
          # - name: DB_PASSWORD
          #   value: Eh?3U~_sh#X@u&+K
          - name: DB_URL
            value: "jdbc:postgresql://host.minikube.internal:5432/users"
          - name: DB_USERNAME
            value: admin
          - name: DB_PASSWORD
            value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: hobbit-user
spec:
  selector:
    app: hobbit-user
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082